### ISSUE TITLE
Quality adjustable in future?

### ISSUE THREAD

**Issue by nottheend** [UpAllNite-Software/simple-song-collector#3]
I am not very familoar with the conpression topic, but are there any plans to adjust the quality of the m4a sound files in the future?

Thanks for providing this nice little app 🙏

**Comment by teststation5** [comment]
y'know, I'm not real sure that would be possible.  The song collector just scans the available audio only formats that youtube presents.  I think for videos there is likely only one or maybe two choices.  For the music links, there may be a couple options.  I will have to review the logic for how I pick which one it downloads...   Anyway, would you be looking for the highest quality option or one of the lower quality options?

**Comment by nottheend** [comment]
Thank you! Yeah, most likely I am interested in the rather higher quality.
My ultimate goal is to upload it to my Subsonic server. For that I also need to enrich the songs with metadata, which would be Feature Request. Considering the name of the project, I refrain from it, but for background information :)

**Comment by teststation5** [comment]
I looked through the logic and it was just selecting the first m4a stream.  Changed it to get the m4a stream with the highest bitrate.  As far as meta data...  I think I am extracting everything usable and dependable from the youtube link.  If there is something else available that you are looking for, let me know and I will see if it can be gathered.

**Comment by nottheend** [comment]
It is perfectly fine. From my point of view we can close this issue since I inteded to get the highes quality. And I really LOVE the feature that you extract metadata as well!!!
